version: 2

jobs:
  build:
    docker:
      - image: swift:4.0
    steps:
      - run: apt-get install -y libssl-dev postgresql
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test
